quarkus.http.port=${{ values.port }}
quarkus.application.name=${{ values.name }}

# OpenAPI
quarkus.smallrye-openapi.info-title=${{ values.name }}
quarkus.smallrye-openapi.info-version=1.0.0

# Health
quarkus.smallrye-health.root-path=/health

# OpenTelemetry
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.service.name=${{ values.name }}

# OpenShift deployment
quarkus.openshift.route.expose=true
quarkus.openshift.labels."app.kubernetes.io/part-of"=${{ values.artifactId }}
